<!-- Trabalho Desenvolvido na Data Science Academy - www.datascienceacademy.com.br -->
# <font color='blue'>Data Science Academy</font>
# <font color='blue'>Fundamentos de Linguagem Python - Do Básico a Aplicações de IA</font>
# <font color='blue'>Lista 4 de Exercícios</font>

In [1]:
# Imports
import pandas as pd
import numpy as np

#### Exercício 1: Seleção de Dados Condicional

A partir do DataFrame de funcionários abaixo, selecione e exiba apenas os funcionários do departamento de 'Vendas' que têm um salário superior a R$ 4.500.

In [3]:
# Dados de exemplo
dados = {'Nome': ['Ana', 'Bruno', 'Carla', 'Matias', 'Eliana', 'Fabiano'],
         'Departamento': ['RH', 'Vendas', 'TI', 'Vendas', 'RH', 'Vendas'],
         'Salário': [4000, 5000, 6200, 4400, 4300, 5500]}

In [4]:
# DataFrame
df_funcionarios = pd.DataFrame(dados)

In [5]:
df_funcionarios

      Nome Departamento  Salário
0      Ana           RH     4000
1    Bruno       Vendas     5000
2    Carla           TI     6200
3   Matias       Vendas     4400
4   Eliana           RH     4300
5  Fabiano       Vendas     5500

In [90]:
# Solução
depto_vendas = df_funcionarios['Departamento'] == 'Vendas'
mais_4500 = df_funcionarios['Salário'] >= 4500
resultado = df_funcionarios[depto_vendas & mais_4500]
resultado

      Nome Departamento  Salário
1    Bruno       Vendas     5000
5  Fabiano       Vendas     5500

#### Exercício 2: Agrupamento e Agregação (groupby)

Com o DataFrame de vendas abaixo, calcule o total de vendas (Valor) para cada categoria de produto.

In [9]:
# Dados de exemplo
dados_vendas = {'Categoria': ['Eletrônicos', 'Vestuário', 'Eletrônicos', 'Casa', 'Vestuário', 'Eletrônicos'],
                'Produto': ['TV', 'Camiseta', 'Notebook', 'Sofá', 'Calça', 'Celular'],
                'Valor': [2500, 80, 4500, 1500, 120, 3000]}

In [10]:
# DataFrame
df_vendas = pd.DataFrame(dados_vendas)

In [11]:
df_vendas

     Categoria   Produto  Valor
0  Eletrônicos        TV   2500
1    Vestuário  Camiseta     80
2  Eletrônicos  Notebook   4500
3         Casa      Sofá   1500
4    Vestuário     Calça    120
5  Eletrônicos   Celular   3000

In [91]:
# Solução
agregacao_categoria = df_vendas.groupby('Categoria').agg(Valor = ('Valor', 'sum'))
agregacao_categoria

             Valor
Categoria
Casa          1500
Eletrônicos  10000
Vestuário      200

#### Exercício 3: Criação de Nova Coluna
<!-- Trabalho Desenvolvido na Data Science Academy - www.datascienceacademy.com.br -->
A partir do DataFrame de produtos abaixo, crie uma nova coluna chamada Preco_com_Desconto que contenha o valor da coluna Preco com 10% de desconto.

In [14]:
# Dados de exemplo
dados_produtos = {'Produto': ['Monitor', 'Teclado', 'Mouse', 'Webcam'],
                  'Preco': [800, 120, 70, 250]}

In [15]:
# DataFrame
df_produtos = pd.DataFrame(dados_produtos)

In [16]:
df_produtos

   Produto  Preco
0  Monitor    800
1  Teclado    120
2    Mouse     70
3   Webcam    250

In [19]:
# Solução
df_produtos['Preco_com_Desconto'] = df_produtos['Preco'] * 0.9
df_produtos

   Produto  Preco  Preco_com_Desconto
0  Monitor    800               720.0
1  Teclado    120               108.0
2    Mouse     70                63.0
3   Webcam    250               225.0

#### Exercício 4: Tratamento de Dados Ausentes (NaN)

No DataFrame de alunos abaixo, substitua as notas ausentes (NaN) pela média da turma (média da coluna 'Nota').

In [20]:
# Dados de exemplo
dados_alunos = {'Aluno': ['Alice', 'Bernardo', 'Clara', 'Marcelo'],
                'Nota': [8.5, 7.0, np.nan, 9.0]}

In [21]:
# DataFrame
df_alunos = pd.DataFrame(dados_alunos)

In [36]:
df_alunos

      Aluno      Nota
0     Alice  8.500000
1  Bernardo  7.000000
2     Clara  8.166667
3   Marcelo  9.000000

In [40]:
# Solução
media_nota = df_alunos['Nota'].mean()
df_alunos.fillna({'Nota': media_nota}, inplace = True)

      Aluno      Nota
0     Alice  8.500000
1  Bernardo  7.000000
2     Clara  8.166667
3   Marcelo  9.000000

#### Exercício 5: Ordenação de Dados (sort_values)

Ordene o DataFrame de pontuações abaixo, do maior para o menor com base na coluna 'Pontos' e exiba o resultado.

In [41]:
# Dados de exemplo
dados_pontuacao = {'Jogador': ['J1', 'J2', 'J3', 'J4', 'J5'],
                   'Pontos': [88, 95, 74, 102, 95]}

In [42]:
# DataFrame
df_pontuacao = pd.DataFrame(dados_pontuacao)

In [43]:
df_pontuacao

  Jogador  Pontos
0      J1      88
1      J2      95
2      J3      74
3      J4     102
4      J5      95

In [53]:
# Solução
df_pontuacao['Pontos'].sort_values(ascending = False)

3    102
4     95
1     95
0     88
2     74
Name: Pontos, dtype: int64

#### Exercício 6: Combinação de DataFrames (merge)

Combine os DataFrames df_clientes e df_pedidos com base na coluna em comum ID_Cliente.

In [54]:
# Dados de exemplo
df_clientes = pd.DataFrame({'ID_Cliente': [1, 2, 3],
                            'Nome': ['Carlos', 'Mariana', 'Lucas']})

In [55]:
# Dados de exemplo
df_pedidos = pd.DataFrame({'ID_Pedido': [101, 102, 103],
                           'ID_Cliente': [2, 1, 2],
                           'Produto': ['Livro', 'Caneta', 'Caderno']})

In [58]:
# Solução
df_merge = pd.merge(df_clientes, df_pedidos, on = 'ID_Cliente', how = 'inner')
print(df_merge)

   ID_Cliente     Nome  ID_Pedido  Produto
0           2  Mariana        103  Caderno
1           2  Mariana        101    Livro
2           1   Carlos        102   Caneta

#### Exercício 7: Manipulação de Strings (.str)
<!-- Trabalho Desenvolvido na Data Science Academy - www.datascienceacademy.com.br -->
No DataFrame abaixo, extraia o ano da coluna Data e crie uma nova coluna chamada Ano.

In [59]:
# Dados de exemplo
dados_eventos = {'Evento': ['Conferência A', 'Workshop B', 'Feira C'],
                 'Data': ['2025-10-25', '2026-03-12', '2026-09-01']}

In [60]:
# DataFrame
df_eventos = pd.DataFrame(dados_eventos)

In [61]:
df_eventos

          Evento        Data
0  Conferência A  2025-10-25
1     Workshop B  2026-03-12
2        Feira C  2026-09-01

In [69]:
# Solução
df_eventos['Ano'] = df_eventos['Data']
df_eventos['Ano'] = pd.to_datetime(df_eventos['Ano'])
df_eventos['Ano'] = df_eventos['Ano'].dt.year
df_eventos

          Evento        Data   Ano
0  Conferência A  2025-10-25  2025
1     Workshop B  2026-03-12  2026
2        Feira C  2026-09-01  2026

#### Exercício 8: Uso do Método apply

Crie uma nova coluna Status no DataFrame de notas. Se a Nota for maior ou igual a 7, o status deve ser 'Aprovado', caso contrário, 'Reprovado'. Use o método apply.

In [70]:
# Dados de exemplo
dados_notas = {'Aluno': ['Maria', 'Jeremias', 'Paulo', 'Roberto'],
               'Nota': [9.5, 6.0, 5.5, 8.0]}

In [71]:
# DataFrame
df_notas = pd.DataFrame(dados_notas)

In [72]:
df_notas

      Aluno  Nota
0     Maria   9.5
1  Jeremias   6.0
2     Paulo   5.5
3   Roberto   8.0

In [73]:
# Solução
df_notas['Status'] = df_notas['Nota'].apply(lambda n: 'Aprovado' if n >= 7 else 'Reprovado')
df_notas

      Aluno  Nota     Status
0     Maria   9.5   Aprovado
1  Jeremias   6.0  Reprovado
2     Paulo   5.5  Reprovado
3   Roberto   8.0   Aprovado

#### Exercício 9: Criação de Tabela Dinâmica (pivot_table)
<!-- Trabalho Desenvolvido na Data Science Academy - www.datascienceacademy.com.br -->
Crie uma tabela dinâmica que mostre a soma das Vendas por Regiao e Vendedor.

In [74]:
# Dados de exemplo
dados_regional = {'Regiao': ['Norte', 'Sul', 'Norte', 'Sul', 'Norte', 'Sul'],
                  'Vendedor': ['Ana', 'Bruno', 'Ana', 'Carlos', 'Carlos', 'Bruno'],
                  'Vendas': [1000, 1500, 1200, 1800, 800, 1300]}

In [75]:
# DataFrame
df_regional = pd.DataFrame(dados_regional)

In [76]:
df_regional

  Regiao Vendedor  Vendas
0  Norte      Ana    1000
1    Sul    Bruno    1500
2  Norte      Ana    1200
3    Sul   Carlos    1800
4  Norte   Carlos     800
5    Sul    Bruno    1300

In [79]:
# Solução
tabela_dinamica = df_regional.pivot_table(values = 'Vendas',
                                          index = 'Regiao',
                                          columns = 'Vendedor',
                                          aggfunc = 'sum',
                                          fill_value = 0)
tabela_dinamica

Vendedor   Ana  Bruno  Carlos
Regiao
Norte     2200      0     800
Sul          0   2800    1800

#### Exercício 10: Análise de Séries Temporais

A partir do DataFrame de visitas a um site, selecione e exiba apenas os registros do mês de agosto de 2026.

In [80]:
# Dados de exemplo
datas = pd.to_datetime(pd.date_range(start = '2026-07-25', periods = 15, freq = 'D'))
dados_visitas = {'Visitas': [150, 165, 178, 199, 205, 210, 225, 230, 215, 240, 255, 260, 245, 250, 270]}
df_visitas = pd.DataFrame(data = dados_visitas, index = datas)
df_visitas.index.name = 'Data'

In [81]:
df_visitas

            Visitas
Data
2026-07-25      150
2026-07-26      165
2026-07-27      178
2026-07-28      199
2026-07-29      205
2026-07-30      210
2026-07-31      225
2026-08-01      230
2026-08-02      215
2026-08-03      240
2026-08-04      255
2026-08-05      260
2026-08-06      245
2026-08-07      250
2026-08-08      270

In [86]:
# Solução

KeyError: 'Agosto'

# Fim